# Generated by Django 5.1.2 on 2024-10-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignee',
            name='email',
            field=models.EmailField(max_length=100, null=True, verbose_name='Assignee Email'),
        ),
    ]
