# Generated by Django 5.1.2 on 2024-11-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_todo_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.TextField(default='test', max_length=100, verbose_name='Task title'),
        ),
    ]
