# Generated by Django 5.1.2 on 2024-11-12 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_subtask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='Title',
            new_name='title',
        ),
    ]
